import pyautogui, time
x = 1
time.sleep(3)
pyautogui.typewrite("pls daily")
pyautogui.press("enter")
time.sleep(3)
while x == 1:
    time.sleep(6)
    pyautogui.typewrite("pls beg")
    pyautogui.press("enter")
    time.sleep(6)
    pyautogui.typewrite("pls pm")
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.typewrite("D")
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.typewrite("pls hunt")
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.typewrite("pls fish")
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.typewrite("pls slots 100")
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.typewrite("pls gamble 100")
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.typewrite("pls rich")
    pyautogui.press("enter")
    time.sleep(5)
    pyautogui.typewrite("pls dep all")
    pyautogui.press("enter")
    time.sleep(6)
    pyautogui.typewrite("pls bal")
    pyautogui.press("enter")
    time.sleep(6)
print("something's wrong")
